[package]
name = "bool-cfg"
version = "0.1.0"
authors = ["tur461"]
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dev-dependencies]
rustversion = "1.0"
trybuild = { version = "1.0.49", features = ["diff"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
